package cl_modelos_pojos;
// Generated 6/04/2017 10:15:51 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * EtapasPlanta generated by hbm2java
 */
@Entity
@Table(name="etapas_planta"
    ,schema="public"
)
public class EtapasPlanta  implements java.io.Serializable {


     private EtapasPlantaId id;
     private Etapas etapas;
     private Plantas plantas;
     private int precioVenta;
     private Integer precioCompra;
     private Set<PlantaVentas> plantaVentases = new HashSet<PlantaVentas>(0);
     private Set<PlantasCompra> plantasCompras = new HashSet<PlantasCompra>(0);
     private Set<PerdidasPlanta> perdidasPlantas = new HashSet<PerdidasPlanta>(0);

    public EtapasPlanta() {
    }

	
    public EtapasPlanta(EtapasPlantaId id, Etapas etapas, Plantas plantas, int precioVenta) {
        this.id = id;
        this.etapas = etapas;
        this.plantas = plantas;
        this.precioVenta = precioVenta;
    }
    public EtapasPlanta(EtapasPlantaId id, Etapas etapas, Plantas plantas, int precioVenta, Integer precioCompra, Set<PlantaVentas> plantaVentases, Set<PlantasCompra> plantasCompras, Set<PerdidasPlanta> perdidasPlantas) {
       this.id = id;
       this.etapas = etapas;
       this.plantas = plantas;
       this.precioVenta = precioVenta;
       this.precioCompra = precioCompra;
       this.plantaVentases = plantaVentases;
       this.plantasCompras = plantasCompras;
       this.perdidasPlantas = perdidasPlantas;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="plantasId", column=@Column(name="plantas_id", nullable=false) ), 
        @AttributeOverride(name="etapasId", column=@Column(name="etapas_id", nullable=false) ) } )
    public EtapasPlantaId getId() {
        return this.id;
    }
    
    public void setId(EtapasPlantaId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="etapas_id", nullable=false, insertable=false, updatable=false)
    public Etapas getEtapas() {
        return this.etapas;
    }
    
    public void setEtapas(Etapas etapas) {
        this.etapas = etapas;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="plantas_id", nullable=false, insertable=false, updatable=false)
    public Plantas getPlantas() {
        return this.plantas;
    }
    
    public void setPlantas(Plantas plantas) {
        this.plantas = plantas;
    }

    
    @Column(name="precioVenta", nullable=false)
    public int getPrecioVenta() {
        return this.precioVenta;
    }
    
    public void setPrecioVenta(int precioVenta) {
        this.precioVenta = precioVenta;
    }

    
    @Column(name="precioCompra")
    public Integer getPrecioCompra() {
        return this.precioCompra;
    }
    
    public void setPrecioCompra(Integer precioCompra) {
        this.precioCompra = precioCompra;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="etapasPlanta")
    public Set<PlantaVentas> getPlantaVentases() {
        return this.plantaVentases;
    }
    
    public void setPlantaVentases(Set<PlantaVentas> plantaVentases) {
        this.plantaVentases = plantaVentases;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="etapasPlanta")
    public Set<PlantasCompra> getPlantasCompras() {
        return this.plantasCompras;
    }
    
    public void setPlantasCompras(Set<PlantasCompra> plantasCompras) {
        this.plantasCompras = plantasCompras;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="etapasPlanta")
    public Set<PerdidasPlanta> getPerdidasPlantas() {
        return this.perdidasPlantas;
    }
    
    public void setPerdidasPlantas(Set<PerdidasPlanta> perdidasPlantas) {
        this.perdidasPlantas = perdidasPlantas;
    }




}


