package cl_modelos_pojos;
// Generated 6/04/2017 10:15:51 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Etapas generated by hbm2java
 */
@Entity
@Table(name="etapas"
    ,schema="public"
)
public class Etapas  implements java.io.Serializable {


     private int id;
     private String nombre;
     private String descripcion;
     private Set<EtapasPlanta> etapasPlantas = new HashSet<EtapasPlanta>(0);

    public Etapas() {
    }

	
    public Etapas(int id, String nombre, String descripcion) {
        this.id = id;
        this.nombre = nombre;
        this.descripcion = descripcion;
    }
    public Etapas(int id, String nombre, String descripcion, Set<EtapasPlanta> etapasPlantas) {
       this.id = id;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.etapasPlantas = etapasPlantas;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="nombre", nullable=false)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="descripcion", nullable=false, length=100)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="etapas")
    public Set<EtapasPlanta> getEtapasPlantas() {
        return this.etapasPlantas;
    }
    
    public void setEtapasPlantas(Set<EtapasPlanta> etapasPlantas) {
        this.etapasPlantas = etapasPlantas;
    }




}


