package cl_modelos_pojos;
// Generated 6/04/2017 10:15:51 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PlantasCompra generated by hbm2java
 */
@Entity
@Table(name="plantas_compra"
    ,schema="public"
)
public class PlantasCompra  implements java.io.Serializable {


     private int id;
     private ComprasPlanta comprasPlanta;
     private EtapasPlanta etapasPlanta;
     private int cantidad;
     private Integer descuento;

    public PlantasCompra() {
    }

	
    public PlantasCompra(int id, ComprasPlanta comprasPlanta, EtapasPlanta etapasPlanta, int cantidad) {
        this.id = id;
        this.comprasPlanta = comprasPlanta;
        this.etapasPlanta = etapasPlanta;
        this.cantidad = cantidad;
    }
    public PlantasCompra(int id, ComprasPlanta comprasPlanta, EtapasPlanta etapasPlanta, int cantidad, Integer descuento) {
       this.id = id;
       this.comprasPlanta = comprasPlanta;
       this.etapasPlanta = etapasPlanta;
       this.cantidad = cantidad;
       this.descuento = descuento;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_compras_planta", nullable=false)
    public ComprasPlanta getComprasPlanta() {
        return this.comprasPlanta;
    }
    
    public void setComprasPlanta(ComprasPlanta comprasPlanta) {
        this.comprasPlanta = comprasPlanta;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumns( { 
        @JoinColumn(name="plantas_id", referencedColumnName="plantas_id", nullable=false), 
        @JoinColumn(name="etapas_id", referencedColumnName="etapas_id", nullable=false) } )
    public EtapasPlanta getEtapasPlanta() {
        return this.etapasPlanta;
    }
    
    public void setEtapasPlanta(EtapasPlanta etapasPlanta) {
        this.etapasPlanta = etapasPlanta;
    }

    
    @Column(name="cantidad", nullable=false)
    public int getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(int cantidad) {
        this.cantidad = cantidad;
    }

    
    @Column(name="descuento")
    public Integer getDescuento() {
        return this.descuento;
    }
    
    public void setDescuento(Integer descuento) {
        this.descuento = descuento;
    }




}


