package cl_modelos_pojos;
// Generated 6/04/2017 10:15:51 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Suministros generated by hbm2java
 */
@Entity
@Table(name="suministros"
    ,schema="public"
)
public class Suministros  implements java.io.Serializable {


     private int id;
     private String nombre;
     private String descripcion;
     private int visibilidad;
     private Integer precioVenta;
     private Integer precioCompra;
     private Set<SuministrosVenta> suministrosVentas = new HashSet<SuministrosVenta>(0);
     private Set<SuministrosCompra> suministrosCompras = new HashSet<SuministrosCompra>(0);

    public Suministros() {
    }

	
    public Suministros(int id, String nombre, String descripcion, int visibilidad) {
        this.id = id;
        this.nombre = nombre;
        this.descripcion = descripcion;
        this.visibilidad = visibilidad;
    }
    public Suministros(int id, String nombre, String descripcion, int visibilidad, Integer precioVenta, Integer precioCompra, Set<SuministrosVenta> suministrosVentas, Set<SuministrosCompra> suministrosCompras) {
       this.id = id;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.visibilidad = visibilidad;
       this.precioVenta = precioVenta;
       this.precioCompra = precioCompra;
       this.suministrosVentas = suministrosVentas;
       this.suministrosCompras = suministrosCompras;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="nombre", nullable=false)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="descripcion", nullable=false, length=100)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    
    @Column(name="visibilidad", nullable=false)
    public int getVisibilidad() {
        return this.visibilidad;
    }
    
    public void setVisibilidad(int visibilidad) {
        this.visibilidad = visibilidad;
    }

    
    @Column(name="precioVenta")
    public Integer getPrecioVenta() {
        return this.precioVenta;
    }
    
    public void setPrecioVenta(Integer precioVenta) {
        this.precioVenta = precioVenta;
    }

    
    @Column(name="precioCompra")
    public Integer getPrecioCompra() {
        return this.precioCompra;
    }
    
    public void setPrecioCompra(Integer precioCompra) {
        this.precioCompra = precioCompra;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="suministros")
    public Set<SuministrosVenta> getSuministrosVentas() {
        return this.suministrosVentas;
    }
    
    public void setSuministrosVentas(Set<SuministrosVenta> suministrosVentas) {
        this.suministrosVentas = suministrosVentas;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="suministros")
    public Set<SuministrosCompra> getSuministrosCompras() {
        return this.suministrosCompras;
    }
    
    public void setSuministrosCompras(Set<SuministrosCompra> suministrosCompras) {
        this.suministrosCompras = suministrosCompras;
    }




}


