package cl_modelos_pojos;
// Generated 21/04/2017 04:49:38 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Clientes generated by hbm2java
 */
@Entity
@Table(name="clientes"
    ,schema="public"
)
public class Clientes  implements java.io.Serializable {


     private int cedula;
     private String nombre;
     private String apellido;
     private String telefono;
     private String correo;
     private Set<VentaSuministros> ventaSuministroses = new HashSet<VentaSuministros>(0);
     private Set<VentasPlanta> ventasPlantas = new HashSet<VentasPlanta>(0);
     private Set<PeticionServicios> peticionServicioses = new HashSet<PeticionServicios>(0);

    public Clientes() {
    }

	
    public Clientes(int cedula, String nombre, String apellido, String telefono, String correo) {
        this.cedula = cedula;
        this.nombre = nombre;
        this.apellido = apellido;
        this.telefono = telefono;
        this.correo = correo;
    }
    public Clientes(int cedula, String nombre, String apellido, String telefono, String correo, Set<VentaSuministros> ventaSuministroses, Set<VentasPlanta> ventasPlantas, Set<PeticionServicios> peticionServicioses) {
       this.cedula = cedula;
       this.nombre = nombre;
       this.apellido = apellido;
       this.telefono = telefono;
       this.correo = correo;
       this.ventaSuministroses = ventaSuministroses;
       this.ventasPlantas = ventasPlantas;
       this.peticionServicioses = peticionServicioses;
    }
   
    public String getNombreCompleto() {
        return this.nombre + this.apellido;
    }
     @Id 

    
    @Column(name="cedula", unique=true, nullable=false)
    public int getCedula() {
        return this.cedula;
    }
    
    public void setCedula(int cedula) {
        this.cedula = cedula;
    }

    
    @Column(name="nombre", nullable=false)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="apellido", nullable=false)
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }

    
    @Column(name="telefono", nullable=false)
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }

    
    @Column(name="correo", nullable=false)
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="clientes")
    public Set<VentaSuministros> getVentaSuministroses() {
        return this.ventaSuministroses;
    }
    
    public void setVentaSuministroses(Set<VentaSuministros> ventaSuministroses) {
        this.ventaSuministroses = ventaSuministroses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="clientes")
    public Set<VentasPlanta> getVentasPlantas() {
        return this.ventasPlantas;
    }
    
    public void setVentasPlantas(Set<VentasPlanta> ventasPlantas) {
        this.ventasPlantas = ventasPlantas;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="clientes")
    public Set<PeticionServicios> getPeticionServicioses() {
        return this.peticionServicioses;
    }
    
    public void setPeticionServicioses(Set<PeticionServicios> peticionServicioses) {
        this.peticionServicioses = peticionServicioses;
    }




}


