package cl_modelos_pojos;
// Generated 21/04/2017 04:49:38 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CompraSuministros generated by hbm2java
 */
@Entity
@Table(name="compra_suministros"
    ,schema="public"
)
public class CompraSuministros  implements java.io.Serializable {


     private int id;
     private Proveedores proveedores;
     private Date fecha;
     private int nroFactura;
     private Set<SuministrosCompra> suministrosCompras = new HashSet<SuministrosCompra>(0);

    public CompraSuministros() {
    }

	
    public CompraSuministros(int id, Proveedores proveedores, Date fecha, int nroFactura) {
        this.id = id;
        this.proveedores = proveedores;
        this.fecha = fecha;
        this.nroFactura = nroFactura;
    }
    public CompraSuministros(int id, Proveedores proveedores, Date fecha, int nroFactura, Set<SuministrosCompra> suministrosCompras) {
       this.id = id;
       this.proveedores = proveedores;
       this.fecha = fecha;
       this.nroFactura = nroFactura;
       this.suministrosCompras = suministrosCompras;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="proveedores_cedula", nullable=false)
    public Proveedores getProveedores() {
        return this.proveedores;
    }
    
    public void setProveedores(Proveedores proveedores) {
        this.proveedores = proveedores;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha", nullable=false, length=13)
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    
    @Column(name="nro_factura", nullable=false)
    public int getNroFactura() {
        return this.nroFactura;
    }
    
    public void setNroFactura(int nroFactura) {
        this.nroFactura = nroFactura;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="compraSuministros")
    public Set<SuministrosCompra> getSuministrosCompras() {
        return this.suministrosCompras;
    }
    
    public void setSuministrosCompras(Set<SuministrosCompra> suministrosCompras) {
        this.suministrosCompras = suministrosCompras;
    }




}


