package cl_modelos_pojos;
// Generated 7/04/2017 03:07:58 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * EmpleadosServicios generated by hbm2java
 */
@Entity
@Table(name="empleados_servicios"
    ,schema="public"
)
public class EmpleadosServicios  implements java.io.Serializable {


     private EmpleadosServiciosId id;
     private Empleados empleados;
     private PeticionServicios peticionServicios;
     private Date fechaInicio;
     private Date fechaFin;

    public EmpleadosServicios() {
    }

    public EmpleadosServicios(EmpleadosServiciosId id, Empleados empleados, PeticionServicios peticionServicios, Date fechaInicio, Date fechaFin) {
       this.id = id;
       this.empleados = empleados;
       this.peticionServicios = peticionServicios;
       this.fechaInicio = fechaInicio;
       this.fechaFin = fechaFin;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="empleadoCedula", column=@Column(name="empleado_cedula", nullable=false) ), 
        @AttributeOverride(name="peticionServiciosId", column=@Column(name="peticionServicios_id", nullable=false) ) } )
    public EmpleadosServiciosId getId() {
        return this.id;
    }
    
    public void setId(EmpleadosServiciosId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="empleado_cedula", nullable=false, insertable=false, updatable=false)
    public Empleados getEmpleados() {
        return this.empleados;
    }
    
    public void setEmpleados(Empleados empleados) {
        this.empleados = empleados;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="peticionServicios_id", nullable=false, insertable=false, updatable=false)
    public PeticionServicios getPeticionServicios() {
        return this.peticionServicios;
    }
    
    public void setPeticionServicios(PeticionServicios peticionServicios) {
        this.peticionServicios = peticionServicios;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha_inicio", nullable=false, length=13)
    public Date getFechaInicio() {
        return this.fechaInicio;
    }
    
    public void setFechaInicio(Date fechaInicio) {
        this.fechaInicio = fechaInicio;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha_fin", nullable=false, length=13)
    public Date getFechaFin() {
        return this.fechaFin;
    }
    
    public void setFechaFin(Date fechaFin) {
        this.fechaFin = fechaFin;
    }




}


