package cl_modelos_pojos;
// Generated 21/04/2017 04:49:38 AM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Empleados generated by hbm2java
 */
@Entity
@Table(name = "empleados",
         schema = "public"
)
public class Empleados implements java.io.Serializable {

    private int cedula;
    private String nombre;
    private String apellido;
    private String telefono;
    private String correo;
    private String hojaDeVida;
    private Set<VentasPlanta> ventasPlantas = new HashSet<VentasPlanta>(0);
    private Set<VentaSuministros> ventaSuministroses = new HashSet<VentaSuministros>(0);
    private Set<EmpleadosServicios> empleadosServicioses = new HashSet<EmpleadosServicios>(0);

    public Empleados() {
    }

    public Empleados(int cedula, String nombre, String apellido, String telefono, String correo, String hojaDeVida) {
        this.cedula = cedula;
        this.nombre = nombre;
        this.apellido = apellido;
        this.telefono = telefono;
        this.correo = correo;
        this.hojaDeVida = hojaDeVida;
    }

    public Empleados(int cedula, String nombre, String apellido, String telefono, String correo, String hojaDeVida, Set<VentasPlanta> ventasPlantas, Set<VentaSuministros> ventaSuministroses, Set<EmpleadosServicios> empleadosServicioses) {
        this.cedula = cedula;
        this.nombre = nombre;
        this.apellido = apellido;
        this.telefono = telefono;
        this.correo = correo;
        this.hojaDeVida = hojaDeVida;
        this.ventasPlantas = ventasPlantas;
        this.ventaSuministroses = ventaSuministroses;
        this.empleadosServicioses = empleadosServicioses;
    }

    public String getNombreCompleto() {
        return this.nombre + this.apellido;
    }

    @Id

    @Column(name = "cedula", unique = true, nullable = false)
    public int getCedula() {
        return this.cedula;
    }

    public void setCedula(int cedula) {
        this.cedula = cedula;
    }

    @Column(name = "nombre", nullable = false)
    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    @Column(name = "apellido", nullable = false)
    public String getApellido() {
        return this.apellido;
    }

    public void setApellido(String apellido) {
        this.apellido = apellido;
    }

    @Column(name = "telefono", nullable = false)
    public String getTelefono() {
        return this.telefono;
    }

    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }

    @Column(name = "correo", nullable = false)
    public String getCorreo() {
        return this.correo;
    }

    public void setCorreo(String correo) {
        this.correo = correo;
    }

    @Column(name = "hoja_de_vida", nullable = false)
    public String getHojaDeVida() {
        return this.hojaDeVida;
    }

    public void setHojaDeVida(String hojaDeVida) {
        this.hojaDeVida = hojaDeVida;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "empleados")
    public Set<VentasPlanta> getVentasPlantas() {
        return this.ventasPlantas;
    }

    public void setVentasPlantas(Set<VentasPlanta> ventasPlantas) {
        this.ventasPlantas = ventasPlantas;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "empleados")
    public Set<VentaSuministros> getVentaSuministroses() {
        return this.ventaSuministroses;
    }

    public void setVentaSuministroses(Set<VentaSuministros> ventaSuministroses) {
        this.ventaSuministroses = ventaSuministroses;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "empleados")
    public Set<EmpleadosServicios> getEmpleadosServicioses() {
        return this.empleadosServicioses;
    }

    public void setEmpleadosServicioses(Set<EmpleadosServicios> empleadosServicioses) {
        this.empleadosServicioses = empleadosServicioses;
    }

}
