package cl_modelos_pojos;
// Generated 21/04/2017 04:49:38 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * EtapasPlantaId generated by hbm2java
 */
@Embeddable
public class EtapasPlantaId  implements java.io.Serializable {


     private int plantasId;
     private int etapasId;

    public EtapasPlantaId() {
    }

    public EtapasPlantaId(int plantasId, int etapasId) {
       this.plantasId = plantasId;
       this.etapasId = etapasId;
    }
   


    @Column(name="plantas_id", nullable=false)
    public int getPlantasId() {
        return this.plantasId;
    }
    
    public void setPlantasId(int plantasId) {
        this.plantasId = plantasId;
    }


    @Column(name="etapas_id", nullable=false)
    public int getEtapasId() {
        return this.etapasId;
    }
    
    public void setEtapasId(int etapasId) {
        this.etapasId = etapasId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof EtapasPlantaId) ) return false;
		 EtapasPlantaId castOther = ( EtapasPlantaId ) other; 
         
		 return (this.getPlantasId()==castOther.getPlantasId())
 && (this.getEtapasId()==castOther.getEtapasId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getPlantasId();
         result = 37 * result + this.getEtapasId();
         return result;
   }   


}


