package cl_modelos_pojos;
// Generated 7/04/2017 03:07:58 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Mensajes generated by hbm2java
 */
@Entity
@Table(name="mensajes"
    ,schema="public"
)
public class Mensajes  implements java.io.Serializable {


     private int id;
     private Date fecha;
     private String mensaje;
     private String correo;
     private String nombreCompleto;

    public Mensajes() {
    }

    public Mensajes(int id, Date fecha, String mensaje, String correo, String nombreCompleto) {
       this.id = id;
       this.fecha = fecha;
       this.mensaje = mensaje;
       this.correo = correo;
       this.nombreCompleto = nombreCompleto;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha", nullable=false, length=13)
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    
    @Column(name="mensaje", nullable=false)
    public String getMensaje() {
        return this.mensaje;
    }
    
    public void setMensaje(String mensaje) {
        this.mensaje = mensaje;
    }

    
    @Column(name="correo", nullable=false)
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }

    
    @Column(name="nombre_completo", nullable=false)
    public String getNombreCompleto() {
        return this.nombreCompleto;
    }
    
    public void setNombreCompleto(String nombreCompleto) {
        this.nombreCompleto = nombreCompleto;
    }




}


