package cl_modelos_pojos;
// Generated 21/04/2017 04:49:38 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ModificacionesSuministrosVenta generated by hbm2java
 */
@Entity
@Table(name="modificaciones_suministros_venta"
    ,schema="public"
)
public class ModificacionesSuministrosVenta  implements java.io.Serializable {


     private int id;
     private Integer idSuministrosVenta;
     private String campoModificado;
     private String valorCampoModificado;
     private Date fechaModificacion;

    public ModificacionesSuministrosVenta() {
    }

	
    public ModificacionesSuministrosVenta(int id, String campoModificado, Date fechaModificacion) {
        this.id = id;
        this.campoModificado = campoModificado;
        this.fechaModificacion = fechaModificacion;
    }
    public ModificacionesSuministrosVenta(int id, Integer idSuministrosVenta, String campoModificado, String valorCampoModificado, Date fechaModificacion) {
       this.id = id;
       this.idSuministrosVenta = idSuministrosVenta;
       this.campoModificado = campoModificado;
       this.valorCampoModificado = valorCampoModificado;
       this.fechaModificacion = fechaModificacion;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="id_suministros_venta")
    public Integer getIdSuministrosVenta() {
        return this.idSuministrosVenta;
    }
    
    public void setIdSuministrosVenta(Integer idSuministrosVenta) {
        this.idSuministrosVenta = idSuministrosVenta;
    }

    
    @Column(name="campo_modificado", nullable=false)
    public String getCampoModificado() {
        return this.campoModificado;
    }
    
    public void setCampoModificado(String campoModificado) {
        this.campoModificado = campoModificado;
    }

    
    @Column(name="valor_campo_modificado")
    public String getValorCampoModificado() {
        return this.valorCampoModificado;
    }
    
    public void setValorCampoModificado(String valorCampoModificado) {
        this.valorCampoModificado = valorCampoModificado;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha_modificacion", nullable=false, length=13)
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }




}


