package cl_modelos_pojos;
// Generated 6/04/2017 10:15:51 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * MotivosPerdidasPlanta generated by hbm2java
 */
@Entity
@Table(name="motivos_perdidas_planta"
    ,schema="public"
)
public class MotivosPerdidasPlanta  implements java.io.Serializable {


     private int id;
     private String motivo;
     private Set<PerdidasPlanta> perdidasPlantas = new HashSet<PerdidasPlanta>(0);

    public MotivosPerdidasPlanta() {
    }

	
    public MotivosPerdidasPlanta(int id, String motivo) {
        this.id = id;
        this.motivo = motivo;
    }
    public MotivosPerdidasPlanta(int id, String motivo, Set<PerdidasPlanta> perdidasPlantas) {
       this.id = id;
       this.motivo = motivo;
       this.perdidasPlantas = perdidasPlantas;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="motivo", nullable=false)
    public String getMotivo() {
        return this.motivo;
    }
    
    public void setMotivo(String motivo) {
        this.motivo = motivo;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="motivosPerdidasPlanta")
    public Set<PerdidasPlanta> getPerdidasPlantas() {
        return this.perdidasPlantas;
    }
    
    public void setPerdidasPlantas(Set<PerdidasPlanta> perdidasPlantas) {
        this.perdidasPlantas = perdidasPlantas;
    }




}


