package cl_modelos_pojos;
// Generated 7/04/2017 03:07:58 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PeticionServicios generated by hbm2java
 */
@Entity
@Table(name="peticion_servicios"
    ,schema="public"
)
public class PeticionServicios  implements java.io.Serializable {


     private int id;
     private Clientes clientes;
     private Servicios servicios;
     private Date fechaInicio;
     private Date fechaFinal;
     private Integer descuento;
     private String direccion;
     private int costo;
     private Set<EmpleadosServicios> empleadosServicioses = new HashSet<EmpleadosServicios>(0);

    public PeticionServicios() {
    }

	
    public PeticionServicios(int id, Clientes clientes, Servicios servicios, Date fechaInicio, Date fechaFinal, String direccion, int costo) {
        this.id = id;
        this.clientes = clientes;
        this.servicios = servicios;
        this.fechaInicio = fechaInicio;
        this.fechaFinal = fechaFinal;
        this.direccion = direccion;
        this.costo = costo;
    }
    public PeticionServicios(int id, Clientes clientes, Servicios servicios, Date fechaInicio, Date fechaFinal, Integer descuento, String direccion, int costo, Set<EmpleadosServicios> empleadosServicioses) {
       this.id = id;
       this.clientes = clientes;
       this.servicios = servicios;
       this.fechaInicio = fechaInicio;
       this.fechaFinal = fechaFinal;
       this.descuento = descuento;
       this.direccion = direccion;
       this.costo = costo;
       this.empleadosServicioses = empleadosServicioses;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cliente_cedula", nullable=false)
    public Clientes getClientes() {
        return this.clientes;
    }
    
    public void setClientes(Clientes clientes) {
        this.clientes = clientes;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="servicios_id", nullable=false)
    public Servicios getServicios() {
        return this.servicios;
    }
    
    public void setServicios(Servicios servicios) {
        this.servicios = servicios;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha_inicio", nullable=false, length=13)
    public Date getFechaInicio() {
        return this.fechaInicio;
    }
    
    public void setFechaInicio(Date fechaInicio) {
        this.fechaInicio = fechaInicio;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha_final", nullable=false, length=13)
    public Date getFechaFinal() {
        return this.fechaFinal;
    }
    
    public void setFechaFinal(Date fechaFinal) {
        this.fechaFinal = fechaFinal;
    }

    
    @Column(name="descuento")
    public Integer getDescuento() {
        return this.descuento;
    }
    
    public void setDescuento(Integer descuento) {
        this.descuento = descuento;
    }

    
    @Column(name="direccion", nullable=false)
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }

    
    @Column(name="costo", nullable=false)
    public int getCosto() {
        return this.costo;
    }
    
    public void setCosto(int costo) {
        this.costo = costo;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="peticionServicios")
    public Set<EmpleadosServicios> getEmpleadosServicioses() {
        return this.empleadosServicioses;
    }
    
    public void setEmpleadosServicioses(Set<EmpleadosServicios> empleadosServicioses) {
        this.empleadosServicioses = empleadosServicioses;
    }




}


