package cl_modelos_pojos;
// Generated 21/04/2017 04:49:38 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PlantasProveedoresId generated by hbm2java
 */
@Embeddable
public class PlantasProveedoresId  implements java.io.Serializable {


     private int plantasId;
     private int proveedoresCedula;

    public PlantasProveedoresId() {
    }

    public PlantasProveedoresId(int plantasId, int proveedoresCedula) {
       this.plantasId = plantasId;
       this.proveedoresCedula = proveedoresCedula;
    }
   


    @Column(name="plantas_id", nullable=false)
    public int getPlantasId() {
        return this.plantasId;
    }
    
    public void setPlantasId(int plantasId) {
        this.plantasId = plantasId;
    }


    @Column(name="proveedores_cedula", nullable=false)
    public int getProveedoresCedula() {
        return this.proveedoresCedula;
    }
    
    public void setProveedoresCedula(int proveedoresCedula) {
        this.proveedoresCedula = proveedoresCedula;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PlantasProveedoresId) ) return false;
		 PlantasProveedoresId castOther = ( PlantasProveedoresId ) other; 
         
		 return (this.getPlantasId()==castOther.getPlantasId())
 && (this.getProveedoresCedula()==castOther.getProveedoresCedula());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getPlantasId();
         result = 37 * result + this.getProveedoresCedula();
         return result;
   }   


}


