package cl_modelos_pojos;
// Generated 6/04/2017 10:15:51 AM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PlantasProveedores generated by hbm2java
 */
@Entity
@Table(name="plantas_proveedores"
    ,schema="public"
)
public class PlantasProveedores  implements java.io.Serializable {


     private PlantasProveedoresId id;
     private Plantas plantas;
     private Proveedores proveedores;

    public PlantasProveedores() {
    }

    public PlantasProveedores(PlantasProveedoresId id, Plantas plantas, Proveedores proveedores) {
       this.id = id;
       this.plantas = plantas;
       this.proveedores = proveedores;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="plantasId", column=@Column(name="plantas_id", nullable=false) ), 
        @AttributeOverride(name="proveedoresCedula", column=@Column(name="proveedores_cedula", nullable=false) ) } )
    public PlantasProveedoresId getId() {
        return this.id;
    }
    
    public void setId(PlantasProveedoresId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="plantas_id", nullable=false, insertable=false, updatable=false)
    public Plantas getPlantas() {
        return this.plantas;
    }
    
    public void setPlantas(Plantas plantas) {
        this.plantas = plantas;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="proveedores_cedula", nullable=false, insertable=false, updatable=false)
    public Proveedores getProveedores() {
        return this.proveedores;
    }
    
    public void setProveedores(Proveedores proveedores) {
        this.proveedores = proveedores;
    }




}


