package cl_modelos_pojos;
// Generated 7/04/2017 03:07:58 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Servicios generated by hbm2java
 */
@Entity
@Table(name="servicios"
    ,schema="public"
)
public class Servicios  implements java.io.Serializable {


     private int id;
     private String nombre;
     private String descripcion;
     private Set<PeticionServicios> peticionServicioses = new HashSet<PeticionServicios>(0);

    public Servicios() {
    }

	
    public Servicios(String nombre, String descripcion) {
        this.nombre = nombre;
        this.descripcion = descripcion;
    }
    public Servicios(int id, String nombre, String descripcion, Set<PeticionServicios> peticionServicioses) {
       this.id = id;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.peticionServicioses = peticionServicioses;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="nombre", nullable=false)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="descripcion", nullable=false, length=100)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="servicios")
    public Set<PeticionServicios> getPeticionServicioses() {
        return this.peticionServicioses;
    }
    
    public void setPeticionServicioses(Set<PeticionServicios> peticionServicioses) {
        this.peticionServicioses = peticionServicioses;
    }




}


