package cl_modelos_pojos;
// Generated 21/04/2017 04:49:38 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * SuministrosVenta generated by hbm2java
 */
@Entity
@Table(name="suministros_venta"
    ,schema="public"
)
public class SuministrosVenta  implements java.io.Serializable {


     private int id;
     private Suministros suministros;
     private VentaSuministros ventaSuministros;
     private int cantidad;
     private Integer descuento;

    public SuministrosVenta() {
    }

	
    public SuministrosVenta(int id, Suministros suministros, VentaSuministros ventaSuministros, int cantidad) {
        this.id = id;
        this.suministros = suministros;
        this.ventaSuministros = ventaSuministros;
        this.cantidad = cantidad;
    }
    public SuministrosVenta(int id, Suministros suministros, VentaSuministros ventaSuministros, int cantidad, Integer descuento) {
       this.id = id;
       this.suministros = suministros;
       this.ventaSuministros = ventaSuministros;
       this.cantidad = cantidad;
       this.descuento = descuento;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="suministro_id", nullable=false)
    public Suministros getSuministros() {
        return this.suministros;
    }
    
    public void setSuministros(Suministros suministros) {
        this.suministros = suministros;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_venta_suministros", nullable=false)
    public VentaSuministros getVentaSuministros() {
        return this.ventaSuministros;
    }
    
    public void setVentaSuministros(VentaSuministros ventaSuministros) {
        this.ventaSuministros = ventaSuministros;
    }

    
    @Column(name="cantidad", nullable=false)
    public int getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(int cantidad) {
        this.cantidad = cantidad;
    }

    
    @Column(name="descuento")
    public Integer getDescuento() {
        return this.descuento;
    }
    
    public void setDescuento(Integer descuento) {
        this.descuento = descuento;
    }




}


