package cl_modelos_pojos;
// Generated May 21, 2017 9:23:14 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name = "usuario",
         schema = "public"
)
public class Usuario implements java.io.Serializable {

    @Column(name = "correo", unique = true, nullable = false)
    @Id
    private String correo;
    @Column(name = "clave", length = 16)
    private String clave;
    @Column(name = "tipo", length = 1)
    private Character tipo;

    public Usuario() {
    }

    public Usuario(String correo) {
        this.correo = correo;
    }

    public Usuario(String correo, String clave, Character tipo) {
        this.correo = correo;
        this.clave = clave;
        this.tipo = tipo;
    }

    public String getCorreo() {
        return this.correo;
    }

    public void setCorreo(String correo) {
        this.correo = correo;
    }

    public String getClave() {
        return this.clave;
    }

    public void setClave(String clave) {
        this.clave = clave;
    }

    public Character getTipo() {
        return this.tipo;
    }

    public void setTipo(Character tipo) {
        this.tipo = tipo;
    }

}
